# Generated by Django 5.2.12 on 2026-03-08 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.CharField(help_text='Unique assessment ID', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing (Agents Running)'), ('playbook_ready', 'Playbook Ready'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('raw_file_url', models.URLField(blank=True, help_text='Blob URL of the uploaded assessment JSON/CSV', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(help_text='Surveyor, Architect, Accountant, Risk Officer', max_length=50)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='success', max_length=50)),
                ('logs', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='core.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(help_text='Original ID from Azure Migrate', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(help_text='e.g., VM, Database, WebApp', max_length=50)),
                ('properties', models.JSONField(default=dict, help_text='OS, cores, memory, tags, etc.')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(default='network', max_length=50)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='core.assessment')),
                ('source_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_dependencies', to='core.asset')),
                ('target_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_dependencies', to='core.asset')),
            ],
        ),
        migrations.CreateModel(
            name='MigrationWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave_number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('duration_days', models.IntegerField(default=0)),
                ('reasoning', models.TextField(blank=True, help_text='LLM reasoning for this wave sequence')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waves', to='core.assessment')),
                ('assets', models.ManyToManyField(related_name='waves', to='core.asset')),
            ],
            options={
                'ordering': ['wave_number'],
            },
        ),
        migrations.CreateModel(
            name='CostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_monthly_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('projected_monthly_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('estimated_savings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pricing_source', models.CharField(default='Azure Retail Prices API', max_length=255)),
                ('calculation_details', models.JSONField(default=dict, help_text='Breakdown of costs by asset')),
                ('wave', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_model', to='core.migrationwave')),
            ],
        ),
        migrations.CreateModel(
            name='PlaybookVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('payload', models.JSONField(help_text='Full snapshot of the playbook at this version')),
                ('diff_summary', models.TextField(blank=True, help_text='What changed from the previous version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbook_versions', to='core.assessment')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='RiskCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(help_text='e.g., GDPR, SOX, Downtime', max_length=100)),
                ('description', models.TextField()),
                ('is_blocking', models.BooleanField(default=False)),
                ('remediation_plan', models.TextField(blank=True)),
                ('signed_off_by', models.CharField(blank=True, max_length=100, null=True)),
                ('signed_off_at', models.DateTimeField(blank=True, null=True)),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_cards', to='core.migrationwave')),
            ],
        ),
    ]
